// Stand-in for the real /pkg/onius_wasm.js, which is generated by
// `wasm-pack build` and gitignored — it doesn't exist in a fresh checkout
// (e.g. CI's js-unit job, which only runs `npm run test:unit`, no wasm-pack
// step). vitest.config.js aliases the real path to this always-present file
// so Vite's static import resolution never fails.
//
// Tests that need custom behavior (e.g. a specific convert() return value or
// thrown error) call the __set*Impl functions below directly, rather than
// vi.mock('/pkg/onius_wasm.js', ...) — once this path is aliased, vi.mock's
// specifier no longer reliably matches the aliased module, so its mock
// factory silently never applies and the real stub below runs instead.
let convertImpl = () => '';
let initWasmImpl = () => Promise.resolve();

export default (...args) => initWasmImpl(...args);
export const convert = (...args) => convertImpl(...args);
export const extract_archive = () => Promise.resolve([]);
export const compress_files = () => Promise.resolve(new Uint8Array());

export function __setConvertImpl(fn) {
  convertImpl = fn;
}

export function __setInitWasmImpl(fn) {
  initWasmImpl = fn;
}
